import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from fpdf import FPDF
import base64

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="OncoGuard AI",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 1. SETUP & DATA LOADING ---
@st.cache_data
def get_data():
    data = load_breast_cancer()
    # Using first 10 'mean' features for simplicity in manual mode
    # But for full accuracy, we'd ideally use all. keeping to 10 for UI clarity.
    df = pd.DataFrame(data.data, columns=data.feature_names)
    df_mean = df.iloc[:, :10].copy()
    df_mean['target'] = data.target
    return df_mean, data.feature_names[:10], data

df, feature_names, full_data = get_data()

# --- 2. TRAIN MODEL ---
X = df.drop('target', axis=1)
y = df['target']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
model = LogisticRegression()
model.fit(X_scaled, y)

# --- 3. MOCK EHR DATABASE (Feature 5) ---
# Simulating a hospital database
ehr_db = {
    "P-1001": [14.2, 19.8, 92.5, 650.0, 0.09, 0.12, 0.08, 0.05, 0.18, 0.06],  # Malignant-like
    "P-1002": [11.5, 12.3, 75.0, 400.0, 0.08, 0.05, 0.02, 0.01, 0.15, 0.05],  # Benign-like
    "P-1003": [13.0, 21.0, 85.0, 520.0, 0.11, 0.15, 0.09, 0.04, 0.20, 0.07]   # Borderline
}

# --- HELPER: PDF GENERATOR (Feature 3) ---
def create_pdf(patient_id, prediction_text, prob, input_dict):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    pdf.cell(200, 10, txt="Breast Cancer Diagnosis Report", ln=1, align="C")
    pdf.cell(200, 10, txt="Generated by OncoGuard AI", ln=1, align="C")
    pdf.line(10, 30, 200, 30)
    pdf.ln(20)
    
    pdf.cell(200, 10, txt=f"Patient ID: {patient_id}", ln=1)
    pdf.cell(200, 10, txt=f"Diagnosis: {prediction_text}", ln=1)
    pdf.cell(200, 10, txt=f"Confidence Level: {prob:.2f}%", ln=1)
    pdf.ln(10)
    
    pdf.cell(200, 10, txt="Clinical Measurements:", ln=1)
    for key, value in input_dict.items():
        pdf.cell(200, 10, txt=f" - {key}: {value:.2f}", ln=1)
        
    pdf.ln(20)
    pdf.set_font("Arial", size=10, style='I')
    pdf.multi_cell(0, 10, txt="DISCLAIMER: This report is generated by an AI model and is intended for educational/support purposes only. It is not a substitute for professional medical advice.")
    
    return pdf.output(dest="S").encode("latin-1")

# --- APP LAYOUT ---
st.title(" OncoGuard: Advanced Breast Cancer Detection")

# Navigation Tabs
tab1, tab2, tab3 = st.tabs(["Patient Dashboard", "Batch Analysis", "Research Insights"])

# ==========================================
# TAB 1: SINGLE PATIENT DASHBOARD
# ==========================================
with tab1:
    col_input, col_viz = st.columns([1, 2])
    
    # --- Sidebar/Input Section ---
    with col_input:
        st.subheader("Patient Data")
        
        # EHR Integration Switch
        input_mode = st.radio("Input Mode:", ["Manual Entry", "EHR Search (Mock)"])
        
        input_values = []
        
        if input_mode == "EHR Search (Mock)":
            patient_id = st.text_input("Enter Patient ID (e.g., P-1001, P-1002)", "P-1001")
            if patient_id in ehr_db:
                st.success(f"Record Found: {patient_id}")
                current_data = ehr_db[patient_id]
            else:
                st.error("Patient not found. Using default values.")
                current_data = list(df.mean()[:10]) # Default fallback
        else:
            patient_id = "Manual-Entry"
            current_data = list(df.mean()[:10])

        # Generate Sliders (Auto-filled if EHR used)
        user_input_dict = {}
        for i, col in enumerate(feature_names):
            val = st.slider(
                label=col.replace("mean ", "").capitalize(),
                min_value=float(df[col].min()),
                max_value=float(df[col].max()),
                value=float(current_data[i])
            )
            user_input_dict[col] = val
            input_values.append(val)

    # --- Visualization & Result Section ---
    with col_viz:
        # Prediction Logic
        input_array = np.array(input_values).reshape(1, -1)
        input_scaled = scaler.transform(input_array)
        prediction = model.predict(input_scaled)
        probs = model.predict_proba(input_scaled)
        
        mal_prob = probs[0][0]
        benign_prob = probs[0][1]
        
        # Header Result
        st.subheader("Diagnostic Assessment")
        c1, c2, c3 = st.columns(3)
        
        if prediction[0] == 0: # Malignant
            diag_text = "MALIGNANT"
            confidence = mal_prob * 100
            c1.error(f"⚠️ {diag_text}")
        else: # Benign
            diag_text = "BENIGN"
            confidence = benign_prob * 100
            c1.success(f"✅ {diag_text}")
            
        c2.metric("Confidence", f"{confidence:.1f}%")
        
        # PDF Report Button (Feature 3)
        pdf_bytes = create_pdf(patient_id, diag_text, confidence, user_input_dict)
        c3.download_button(
            label="📄 Download Report",
            data=pdf_bytes,
            file_name=f"Report_{patient_id}.pdf",
            mime="application/pdf"
        )
        
        st.divider()

        # FEATURE 1: FEATURE IMPORTANCE (Explainable AI)
        st.write("#### Why this prediction?")
        
        # Calculate contribution: (Coefficient * Input Value (Scaled))
        # This shows how much each feature pushed the decision towards Malignant (negative coef) or Benign (positive coef)
        importance = model.coef_[0] * input_scaled[0]
        feat_df = pd.DataFrame({
            'Feature': [f.replace("mean ", "").capitalize() for f in feature_names],
            'Contribution': importance
        })
        feat_df = feat_df.sort_values(by='Contribution', key=abs, ascending=False)
        
        fig_imp = px.bar(
            feat_df, x='Contribution', y='Feature', orientation='h',
            title="Feature Contribution to Diagnosis (Explainable AI)",
            color='Contribution', color_continuous_scale='RdBu'
        )
        st.plotly_chart(fig_imp, use_container_width=True)
        
        # FEATURE 6: POPULATION COMPARISON
        st.write("#### Population Comparison")
        # Let's compare the most critical feature (Radius) to the population
        target_col = 'mean radius'
        fig_dist = plt.figure(figsize=(10, 3))
        sns.kdeplot(data=df, x=target_col, hue='target', fill=True, palette={0: 'red', 1: 'green'})
        plt.axvline(user_input_dict[target_col], color='blue', linestyle='--', linewidth=3, label='Current Patient')
        plt.title(f"Patient's {target_col} vs Population Distribution")
        plt.legend(['Benign', 'Malignant', 'Patient'])
        st.pyplot(fig_dist)

# ==========================================
# TAB 2: BATCH ANALYSIS (Feature 2)
# ==========================================
with tab2:
    st.header("Batch Processing")
    st.write("Upload a CSV file containing patient data to process multiple records at once.")
    
    uploaded_file = st.file_uploader("Upload CSV", type=["csv"])
    
    if uploaded_file is not None:
        batch_df = pd.read_csv(uploaded_file)
        st.write("Preview of uploaded data:", batch_df.head())
        
        # Ensure columns match (simple validation)
        try:
            # Filter only relevant columns if they exist, or assume order matches
            # For this demo, we assume the CSV has the correct 10 columns
            batch_X = batch_df.iloc[:, :10] 
            batch_scaled = scaler.transform(batch_X)
            batch_preds = model.predict(batch_scaled)
            
            batch_df['AI_Diagnosis'] = ['Benign' if p == 1 else 'Malignant' for p in batch_preds]
            
            st.success("Analysis Complete!")
            st.dataframe(batch_df)
            
            # Download Results
            csv = batch_df.to_csv(index=False).encode('utf-8')
            st.download_button(
                "Download Results CSV",
                csv,
                "batch_results.csv",
                "text/csv",
                key='download-csv'
            )
            
        except Exception as e:
            st.error(f"Error processing file. Ensure columns match the training data. Details: {e}")

# ==========================================
# TAB 3: DATASET INSIGHTS (Feature 6)
# ==========================================
with tab3:
    st.header("Dataset Research & Visualization")
    
    col_viz1, col_viz2 = st.columns(2)
    
    with col_viz1:
        st.subheader("Correlation Heatmap")
        st.write("Shows how different tumor features relate to each other.")
        corr = df.drop('target', axis=1).corr()
        fig_corr, ax = plt.subplots()
        sns.heatmap(corr, cmap='coolwarm', ax=ax)
        st.pyplot(fig_corr)

    with col_viz2:
        st.subheader("Class Distribution")
        st.write("Balance of Malignant vs Benign cases in training data.")
        count_df = df['target'].value_counts().reset_index()
        count_df['Diagnosis'] = count_df['target'].map({0: 'Malignant', 1: 'Benign'})
        fig_pie = px.pie(count_df, values='count', names='Diagnosis', color='Diagnosis',
                         color_discrete_map={'Malignant':'red', 'Benign':'green'})
        st.plotly_chart(fig_pie)